INSERT INTO dwd_order_emp_online_mi(data_source,
                                    order_no,
                                    order_type,
                                    business_type,
                                    ar_no,
                                    order_month,
                                    raw_order_month,
                                    fee_month,
                                    member_code,
                                    member_name,
                                    party_b,
                                    emp_name,
                                    emp_id_no,
                                    mobile,
                                    region,
                                    raw_region,
                                    order_region,
                                    raw_order_region,
                                    order_item,
                                    order_tax_rate,
                                    reward_tax_rate,
                                    is_solo,
                                    is_collect,
                                    is_cross,
                                    is_refund,
                                    is_extra,
                                    is_sup,
                                    is_cancel,
                                    is_diff,
                                    is_ignore,
                                    is_discard,
                                    income_type,
                                    income_reward,
                                    raw_income_reward,
                                    income_order,
                                    raw_income_order,
                                    income_overdue,
                                    income_disabled,
                                    income_added_tax,
                                    income_stable,
                                    income_indv_tax,
                                    serve_count,
                                    supplier_code,
                                    supplier_name,
                                    cost_type,
                                    cost_reward,
                                    sale_emp_name,
                                    serve_emp_id,
                                    sale_emp_id,
                                    serve_dept_id,
                                    sale_dept_id,
                                    order_parm,
                                    indv_net_pay,
                                    indv_income_tax,
                                    income_indv_order,
                                    income_corp_order,
                                    corp_pension_amount,
                                    corp_pension_rate,
                                    indv_pension_amount,
                                    indv_pension_rate,
                                    corp_illness_amount,
                                    corp_illness_rate,
                                    indv_illness_amount,
                                    indv_illness_rate,
                                    corp_work_amount,
                                    corp_work_rate,
                                    indv_work_amount,
                                    indv_work_rate,
                                    corp_unemployed_amount,
                                    corp_unemployed_rate,
                                    indv_unemployed_amount,
                                    indv_unemployed_rate,
                                    corp_birth_amount,
                                    corp_birth_rate,
                                    indv_birth_amount,
                                    indv_birth_rate,
                                    corp_disabled_amount,
                                    corp_disabled_rate,
                                    indv_disabled_amount,
                                    indv_disabled_rate,
                                    corp_serious_illness_amount,
                                    corp_serious_illness_rate,
                                    indv_serious_illness_amount,
                                    indv_serious_illness_rate,
                                    corp_ext_illness_amount,
                                    corp_ext_illness_rate,
                                    indv_ext_illness_amount,
                                    indv_ext_illness_rate,
                                    corp_hospital_amount,
                                    corp_hospital_rate,
                                    indv_hospital_amount,
                                    indv_hospital_rate,
                                    corp_fund_amount,
                                    corp_fund_rate,
                                    indv_fund_amount,
                                    indv_fund_rate,
                                    indv_union_amount,
                                    corp_other_amount,
                                    indv_other_amount,
                                    debit_card_no,
                                    bank_name,
                                    bank_region,
                                    tax_corp,
                                    raw_create_time,
                                    comment,
                                    raw_order_no,
                                    batch_no)
SELECT 10                                                                       AS data_source,
       C.order_no                                                               AS order_no,
       CASE B.service_fee_type
           WHEN 1 THEN 1
           WHEN 2 THEN 8
           ELSE 4096 END                                                        AS order_type,
       64                                                                       AS business_type,
       REPLACE(UUID(), _utf8'-', _utf8'')                                       AS ar_no,
       '202307'                                                                 AS order_month,
       A.order_month                                                            AS raw_order_month,
       A.bill_month                                                             AS fee_month,
       D.member_code                                                            AS member_code,
       D.member_name                                                            AS member_name,
       E.org_name                                                               AS party_b,
       A.name                                                                   AS emp_name,
       AES_DECRYPT(FROM_BASE64(A.id_no), LEFT(UNHEX(SHA1('eyHXTWVo&B69')), 16)) AS emp_id_no,
       ''                                                                       AS mobile,
       A.city_name                                                              AS region,
       A.city_name                                                              AS raw_region,
       A.city_name                                                              AS order_region,
       A.city_name                                                              AS raw_order_region,
       ''                                                                       AS order_item,
       F.fee_rate / 100                                                         AS order_tax_rate,
       F.fee_rate / 100                                                         AS reward_tax_rate,
       IF(B.single_flag = 1, 1, 0)                                              AS is_solo,
       IF(B.single_flag = 1, 0, 1)                                              AS is_collect,
       IF(C.month < '202307', 1, 0)                                             AS is_cross,
       0                                                                        AS is_refund,
       0                                                                        AS is_extra,
       0                                                                        AS is_sup,
       IF(A.valid = 0, 1, 0)                                                    AS is_cancel,
       0                                                                        AS is_diff,
       0                                                                        AS is_ignore,
       0                                                                        AS is_discard,
       CASE G.open_invoice_type WHEN 1 THEN 2 WHEN 2 THEN 1 END                 AS income_type,
       0                                                                        AS income_reward,
       0                                                                        AS raw_income_reward,
       A.amount / 10000                                                         AS income_order,
       A.amount / 10000                                                         AS raw_income_order,
       0                                                                        AS income_overdue,
       0                                                                        AS income_disabled,
       0                                                                        AS income_added_tax,
       0                                                                        AS income_stable,
       0                                                                        AS income_indv_tax,
       1                                                                        AS serve_count,
       IFNULL(K.supplier_code, '')                                              AS supplier_code,
       IFNULL(K.supplier_name, '')                                              AS supplier_name,
       1                                                                        AS cost_type,
       0                                                                        AS cost_reward,
       ''                                                                       AS sale_emp_name,
       -1                                                                       AS serve_emp_id,
       -1                                                                       AS sale_emp_id,
       -1                                                                       AS serve_dept_id,
       -1                                                                       AS sale_dept_id,
       0                                                                        AS order_parm,
       0                                                                        AS indv_net_pay,
       0                                                                        AS indv_income_tax,
       0                                                                        AS income_indv_order,
       0                                                                        AS income_corp_order,
       0                                                                        AS corp_pension_amount,
       0                                                                        AS corp_pension_rate,
       0                                                                        AS indv_pension_amount,
       0                                                                        AS indv_pension_rate,
       0                                                                        AS corp_illness_amount,
       0                                                                        AS corp_illness_rate,
       0                                                                        AS indv_illness_amount,
       0                                                                        AS indv_illness_rate,
       0                                                                        AS corp_work_amount,
       0                                                                        AS corp_work_rate,
       0                                                                        AS indv_work_amount,
       0                                                                        AS indv_work_rate,
       0                                                                        AS corp_unemployed_amount,
       0                                                                        AS corp_unemployed_rate,
       0                                                                        AS indv_unemployed_amount,
       0                                                                        AS indv_unemployed_rate,
       0                                                                        AS corp_birth_amount,
       0                                                                        AS corp_birth_rate,
       0                                                                        AS indv_birth_amount,
       0                                                                        AS indv_birth_rate,
       0                                                                        AS corp_disabled_amount,
       0                                                                        AS corp_disabled_rate,
       0                                                                        AS indv_disabled_amount,
       0                                                                        AS indv_disabled_rate,
       0                                                                        AS corp_serious_illness_amount,
       0                                                                        AS corp_serious_illness_rate,
       0                                                                        AS indv_serious_illness_amount,
       0                                                                        AS indv_serious_illness_rate,
       0                                                                        AS corp_ext_illness_amount,
       0                                                                        AS corp_ext_illness_rate,
       0                                                                        AS indv_ext_illness_amount,
       0                                                                        AS indv_ext_illness_rate,
       0                                                                        AS corp_hospital_amount,
       0                                                                        AS corp_hospital_rate,
       0                                                                        AS indv_hospital_amount,
       0                                                                        AS indv_hospital_rate,
       0                                                                        AS corp_fund_amount,
       0                                                                        AS corp_fund_rate,
       0                                                                        AS indv_fund_amount,
       0                                                                        AS indv_fund_rate,
       0                                                                        AS indv_union_amount,
       0                                                                        AS corp_other_amount,
       0                                                                        AS indv_other_amount,
       ''                                                                       AS debit_card_no,
       ''                                                                       AS bank_name,
       ''                                                                       AS bank_region,
       ''                                                                       AS tax_corp,
       A.create_time                                                            AS raw_create_time,
       ''                                                                       AS comment,
       ''                                                                       AS raw_order_no,
       F.bill_no                                                                AS batch_no
FROM ods_hro_bill_user_project_20240415 A
         LEFT JOIN ods_mbc_member_product_20240415 B ON A.member_product_id = B.m_pr_id
         INNER JOIN ods_hro_bill_project_order_20240415 C ON A.bill_id = C.bill_id AND A.order_id = C.id AND C.valid = 1
         INNER JOIN ods_mbc_member_info_20240415 D ON A.member_id = D.member_id
         LEFT JOIN ods_oprt_boss_organization_20240415 E ON B.org_id = E.org_id
         INNER JOIN ods_hro_bill_20240415 F ON A.bill_id = F.id AND F.valid = 1 AND F.state = 2
         LEFT JOIN ods_basic_org_product_20240415 G ON B.pr_id = G.pr_id
         LEFT JOIN (SELECT DISTINCT H.bill_id, H.id_no, J.supplier_code, J.supplier_name
                    FROM ods_hro_bill_user_salary_20240415 H
                             LEFT JOIN ods_pay_payroll_bill_20240415 I ON I.bill_no = H.order_no AND I.alive_flag = 1
                             LEFT JOIN ods_supplier_info_20240415 J ON J.supplier_id = I.supplier_id
                    WHERE H.valid = 1) K
                   ON K.bill_id = A.bill_id AND A.id_no = K.id_no
WHERE A.valid = 1
  AND DATE_FORMAT(F.out_time, '%Y%m') = '202404';